### ISSUE TITLE
Refactor codeabase

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-web-crawler#50] opened 2023-06-17 16:11 UTC
There is a lot of leftover code from the analysis mode of OptMeowt before it was a separate extension. We should refactor the codebase to make it more clear. One way to refactor is to just remove code and see if the extension still works.

**Comment by OliverWang13** [comment] 2023-06-24 14:33
I went through and deleted a lot of unnecessary code, but this will need more testing to make sure everything is working as intended.

**Comment by SebastianZimmeck** [comment] 2023-06-24 16:27
@OliverWang13 will look into whether we should set up a test framework. @katehausladen will also help out with @sophieeng advising as well.

@OliverWang13 will concretely run the extension with and without refactoring and see if the results are the same (given that both crawls may be a bit different just because). General success rate, total number of DNS links should be about the same. But differences between individual sites may exist.

@katehausladen may provide a testing script.

**Comment by SebastianZimmeck** [comment] 2023-06-24 16:32
We want to remove two columns from the database scheme: uspapi_opted_out and usp_cookies_opted_out. This information is already present in the other columns.

**Comment by katehausladen** [comment] 2023-06-26 04:01
Based on some preliminary testing, the extension seems to work normally after my last commit. The new command to create the sql database is 
```console
CREATE TABLE entries (id INTEGER PRIMARY KEY AUTO_INCREMENT, site_id INTEGER, domain varchar(255), dns_link BOOLEAN, sent_gpc BOOLEAN, uspapi_before_gpc varchar(255), uspapi_after_gpc varchar(255), usp_cookies_before_gpc varchar(255), usp_cookies_after_gpc varchar(255));
```
I will update the wiki (for setting up the SQL db) after we merge this issue into main. We will also need to update the architecture after we finish deleting old code.

**Comment by katehausladen** [comment] 2023-06-28 19:37
In the previous commit, I rearranged some code that actually analyzes each site. After I made the edits, I crawled 1001 sites, and the extension performed significantly better.

Success rate: 98.7%, which is 6% higher than the previous crawl (excludes insecure certificate/reached error page sites)
DNSLs: 51.6%, which is ~2% higher than the previous crawl
USPS: 35.5%, which is ~11% higher than the previous crawl
This is comparing the sites from the new crawl to the same sites in the previous crawl. 

More details on what I changed:
The functions that start and stop analysis had nested functions inside them that were executing at the beginning of the function where they were defined instead of when they were called. I don’t really understand why this was happening (because I think theoretically it shouldn’t), but when I moved the nested function definitions to immediately before their call, the extension performance was way better.
I realized this was happening because I made a debugging table in the db that essentially functioned as a console log, so I could see the order of execution was wrong. I removed the debugging table before I committed the code, but since there is not console log for the extension during crawls, I think it might be useful to keep and set it up such that it’s optional.

**Comment by SebastianZimmeck** [comment] 2023-06-29 06:42
> After I made the edits, I crawled 1001 sites, and the extension performed significantly better.

Excellent, @katehausladen!

> I removed the debugging table before I committed the code, but since there is not console log for the extension during crawls, I think it might be useful to keep and set it up such that it’s optional.

Just for my information, is there a reason why we are not using a console log during crawls but instead a debugging table?

Yes, an option to have the debugging table created during the crawl would be nice (and let's document it in the readme).

**Comment by katehausladen** [comment] 2023-06-29 16:02
Just to clarify, the debugging table functions as a console log for the analysis extension only. We do have a console log for the crawler script, since it runs locally from a terminal. I haven't found an effective way to use a console log for the analysis extension during crawls. I used the browser console to see a console log for the OptMeowt extension [like this](https://stackoverflow.com/questions/12893981/logging-to-console-from-firefox-extension), but that isn't really a great option because all the logs disappear when the browser quits. (During crawls, the browser quits every time the crawler restarts as well as automatically when the crawl finishes.)

**Comment by SebastianZimmeck** [comment] 2023-06-29 20:33
That sounds good to me. So, I would say, let's do as you say, @katehausladen, and let's include something along the lines of [what you comment](https://github.com/privacy-tech-lab/gpc-web-crawler/issues/50#issuecomment-1613463265) in the readme.

**Comment by OliverWang13** [comment] 2023-07-01 00:11
I have tested since the refactoring and it seems to be working properly. I also tested Kate's data processing process and it works great.

**Comment by katehausladen** [comment] 2023-07-01 02:36
I added the optional debugging table. The option to use the debugging table is selected by running the rest api with 
```console
node index.js debug
``` 
(to use the table) versus
```console
node index.js
``` 
(to not use the table). Obviously, if someone chooses to use the debugging table, they must set up the table in the database, too.

I updated the wiki with this information since the instructions for setting up the database and rest api are there.

**Comment by katehausladen** [comment] 2023-07-08 13:31
As I was watching the crawler, I noticed that sometimes, analysis data would be posted before the site even finished loading. I modified the extension so that it does not start analyzing a site until the site has fully loaded. 
I also noticed that the USPAPI is really sensitive to timing (i.e., if we check it too early, it will be undefined, but if we wait long enough, it will have a value). I added longer timeouts to try to accommodate this. 

The result is a slower crawler with a slightly lower success rate, as sites that do not fully load will not be analyzed. Depending on the run, the success rate is somewhere between 95 and 98%, but the data we are collecting is a lot more accurate and consistent.

**Comment by SebastianZimmeck** [comment] 2023-07-08 13:45
Excellent!

**Comment by SebastianZimmeck** [comment] 2023-07-08 17:46
@katehausladen will close this issue once there is nothing more to do here.

**Comment by katehausladen** [comment] 2023-07-09 01:26
I've opened a pull request for this branch with Oliver as a reviewer. I think we've made all the big changes, and any additional changes that relate to testing analysis performance can be done in issue #54.

**Comment by katehausladen** [comment] 2023-07-15 14:18
When I was updating the architecture readme, I found a few more things that needed to be deleted. (keyboard shortcuts out of the manifests as well as the modes.js file)

**Comment by katehausladen** [comment] 2023-07-15 14:24
I'll update the architecture accordingly.

**Closed by katehausladen** 2023-07-15 14:24 UTC
Labels: refactoring
